language: python  # Or the language you're using

# Install dependencies
install:
  - pip install -r requirements.txt  # If you have Python dependencies
  - apt-get update && apt-get install -y pandoc  # Install Pandoc for document conversion

# Define stages (optional but recommended)
stages:
  - test
  - build

jobs:
  include:
    - stage: test
      name: "Run Validations"
      script:
        - python your_validation_script.py  # Run your validation script
    - stage: build
      name: "Generate Word Document"
      script:
        - pandoc your_template.md -o output.docx  # Convert Markdown to Word
      deploy:  # Optional: deploy the generated document
        provider: releases
        api_key: $GITHUB_TOKEN  # Store your GitHub token in Travis CI settings
        file: output.docx
        skip_cleanup: true
        on:
          tags: true  # Only deploy on tags (recommended)

# Environment variables (optional)
env:
  global:
    - GITHUB_TOKEN: secure_your_github_token  # Encrypt your GitHub token

# Trigger builds on pull requests
branches:
  except:
    - /^(?!pr-).*$/  # Only trigger on pull requests (adjust regex if needed)