name: Markdown to Word Generator

on:
  pull_request:
    branches:
      - main  # Run when a PR is created against the main branch

permissions:
  contents: write  # Required to upload artifacts

jobs:
  validate-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Remove trailing whitespaces from Markdown files
        run: |
          for file in *.md; do
            [ -f "$file" ] || continue
            sed -i 's/[ \t]*$//' "$file"
            echo "Cleaned: $file"
          done

      - name: Commit cleaned Markdown files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git commit -am "Auto-clean Markdown files" || echo "No changes to commit"
          git push || echo "No changes to push"

  generate-word:
    needs: validate-markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Generate Word Document
        run: pandoc template.md -o output.docx

      - name: Upload Word Document as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Generated-Word-Document
          path: output.docx

  release:
    needs: generate-word
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Generated Document
        uses: actions/download-artifact@v3
        with:
          name: Generated-Word-Document
          path: .

      - name: Create GitHub Release and Upload Word Document
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v1.0.${{ github.run_number }}" output.docx --title "Generated Word Document" --notes "Auto-generated from Markdown"
